### ISSUE TITLE
If i drag gallery window too fast it stops dragging

### ISSUE THREAD

**Issue by antimony112** [ilovelampadaire/ilov3lampadairwebsite#1]
happens only when dragging down

Edit: it happens only with gallery window

**Comment by Ponali** [comment]
that is an issue with how chrome, or any browser, handles iframes.

the gallery is actually an iframe inside a window, and when you drag down, the browser doesn't update the main website that the mouse has moved, but instead the iframe. since the main website is responsible for moving the windows, the window doesn't move.

a lot of changes will have to be made to put the gallery into its own window, and not with an iframe, so i consider best leaving this unchanged for the while being.
